### ISSUE TITLE
https://3dpass.org/mainnet#mining-pool-rewards Grammar/Spelling error

### ISSUE THREAD

**Issue by misher2** [3Dpass/website#1]
Block rewards = 500 P3D, pool fee = 10 %, validators fee = 30%. After excluding validators fee 150 P3D, the rest 350 P3D will be divided among miniers and pool's admin. 

Change to 

Block rewards = 500 P3D, pool fee = 10 %, validators fee = 30%. After excluding validators fee 150 P3D, the rest 350 P3D will be divided among miners and the pool operator. 

------

In order for the minier to take a share in the block rewards it is required to push at least one correct 3D object, the hash ID of which would be below the additional off-chian difficulty number. All other pushed objects above the limit will not be counted. Assume, we have 3 miners in the pool, which pushed 10 correct 3D objects to, and 1 block was mined.

Change to

In order for the miner to take a share of the block rewards it is required to push at least one correct 3D object, the hash ID of which would be below the additional off-chain difficulty number. All other pushed objects above the limit will not be counted. Assume, we have 3 miners in the pool, which pushed 10 correct 3D objects, and 1 block was mined.

------

Strongly suggest you consider using Grammarly on all website text.

**Comment by PaulSff** [comment]
Thank you for the contribution, the mistakes have been fixed: https://github.com/3Dpass/website/commit/f9e9050024ce4892bcae9747d9dfbf4efdb90163
